#!/bin/python3

def nextMove(posr, posc, board):
    
    r,c = 0,0
    for i in range(len(board)):
        if "d" in board[i]:
            r = i
            c = board[i].index("d")
            
    if r > posr:
        print('DOWN')
    elif r < posr:
        print('UP')
    elif c > posc:
        print('RIGHT')
    elif c < posc:
        print('LEFT')
    else:
        print('CLEAN')
            
   

if __name__ == "__main__":
    pos = [int(i) for i in input().strip().split()]
    board = [[j for j in input().strip()] for i in range(5)]
    nextMove(pos[0], pos[1], board)
