#!/usr/bin/python

# Head ends here

def next_move(posr, posc, board):
    """
    The first line contains two space separated integers which indicate the current position of the bot.
The board is indexed using Matrix Convention
5 lines follow representing the grid. Each cell in the grid is represented by any of the following 3 characters: 'b' (ascii value 98) indicates the bot's current position, 'd' (ascii value 100) indicates a dirty cell and '-' (ascii value 45) indicates a clean cell in the grid.

Note If the bot is on a dirty cell, the cell will still have 'd' on it.
"""
    
    if board[posr][posc] == "d":
        print('CLEAN')
        
    else:
        
        dist = []
        
        for i in range(len(board)):
            for j in range(len(board)):
                if board[i][j] == "d":
                    horz = posr - i
                    vert = posc - j
                    tot = abs(horz) + abs(vert)
                    
                    if tot == 1:  #added to try and catch the easy cases faster
                        if abs(horz) == 1:
                            if horz < 0:
                                move = "RIGHT"
                            else:
                                move = "LEFT"
                        else:
                            if vert < 0:
                                move = "DOWN"
                            else:
                                move = "UP"
                        print(move)
                        return(move)
                            
                    dist.append(tup(tot, horz, vert))       
                
        min_dist = min(dist)
        
        
        for tot, horz, vert in nearest:
            
            if abs(horz) <= abs(vert) and horz != 0:
                if horz < 0:
                    move = "DOWN"
                elif horz > 0:
                    move = "UP"
                    
            else:
                if vert < 0:
                    move = "LEFT"
                elif vert > 0:
                    move = "RIGHT"
                else:
                    move = "Didn't I already tell you to clean?"
                    
        print(move)
        return(move)
                    
        

# Tail starts here

if __name__ == "__main__":
    pos = [int(i) for i in input().strip().split()]
    board = [[j for j in input().strip()] for i in range(5)]
    next_move(pos[0], pos[1], board)
